system as sysdba --conection
-- Task 1 create pdb
CREATE PLUGGABLE DATABASE bo_pdb_29096
  ADMIN USER Boris_plsqlauca_29096 IDENTIFIED BY 1234
  DEFAULT TABLESPACE users
  DATAFILE 'C:\APP\ORADATA\XE\bo_pdb_2914\users01.dbf'
  SIZE 250M AUTOEXTEND ON
  FILE_NAME_CONVERT = ('C:\APP\ORADATA\XE\PDBSEED\', 'C:\APP\ORADATA\XE\be_pdb_29143\');

-- Task  create and delete pdb
CREATE PLUGGABLE DATABASE bo_to_delete_pdb_29096
  ADMIN USER Boris_plsqlauca_29096 IDENTIFIED BY 1234
  DEFAULT TABLESPACE users
  DATAFILE 'C:\APP\ORADATA\XE\bo_to_delete_pdb_2914\users01.dbf'
  SIZE 250M AUTOEXTEND ON
  FILE_NAME_CONVERT = ('C:\APP\ORADATA\XE\PDBSEED\', 'C:\APP\ORADATA\XE\be_to_delete_pdb_29143\');

DROP PLUGGABLE DATABASE bo_to_delete_pdb_29096 INCLUDING DATAFILES;
